### ISSUE TITLE
Why is everything prefixed with `pio`?

### ISSUE THREAD

**Issue by yocontra** [ShaunBaker/PredictionIO-Node-SDK#14]
Kind of annoying to have to take sane data and run it through a prefixer, then run data that comes back through a prefix removal fn. Why does predictionIO do this? I've never seen anything like it in other dbs

**Comment by ShaunBaker** [comment]
Hey

You should ask this [here](https://github.com/PredictionIO/PredictionIO) or [here](https://predictionio.atlassian.net/secure/Dashboard.jspa)
