### ISSUE TITLE
Item Similarity Issue

### ISSUE THREAD

**Issue by prakashbask** [ShaunBaker/PredictionIO-Node-SDK#2]
Hi,
Thanks for starting this project.
I did a npm install for this SDK couple of days back and the version I have is 0.0.4.The implementation of prediction.items.similarity takes in parameter for pio_uid. However, as per the PredictionIO API endpoint specs, this should be pio_iid. 

Can you please confirm?

Thanks,
Prakash

**Comment by ShaunBaker** [comment]
Hey

Thanks for spotting that.

I will make the change and update the NPM version of the module.

Thanks

**Comment by ShaunBaker** [comment]
Change has been made and package updated.
