### ISSUE TITLE
'Official' PredictionIO Node SDK?

### ISSUE THREAD

**Issue by andrew-kzoo** [ShaunBaker/PredictionIO-Node-SDK#3]
Thank you for your great work!

Do you expect this repository to become the 'official' PredictionIO Node SDK?

**Comment by ShaunBaker** [comment]
@dszeto Any comment on this?

**Comment by dszeto** [comment]
@ShaunBaker Sorry for the late reply. We have taken note of this discussion thread and will come back to it shortly.

**Comment by ShaunBaker** [comment]
Hey @andrew-kzoo 

I am intending to actively maintain this if issues come up in future and as prediction.io progresses.

See here for official points:

http://docs.prediction.io/current/contribution/projects.html
