### ISSUE TITLE
recommend and similar use POST instead of GET 

### ISSUE THREAD

**Issue by schwarsi** [ShaunBaker/PredictionIO-Node-SDK#5]
hi, at first thanks for this sdk! 

i think using POST for retrieving recommendations is the wrong method according to the [documentation](docs.prediction.io/current/engines/itemrec/api.html) (the same for similarity). using POST results in a 404 wich is not detected by the tests as there are no checks for correct statusCodes.

**Comment by ShaunBaker** [comment]
This has been amended by the latest pull request.

Updated NPM package will be pushed shortly.
